### PR TITLE
Preserve installation error by wrapping

### LINKED ISSUE #384: Preserve stack trace from installation errors
/priority P3
/kind bug
/kind cleanup

For example if a plugin fails to install I get this stack trace from -v=5:

```
F1113 16:05:52.448852   29304 root.go:56] failed to install some plugins: [whoami]. error=install failed: failed to unpack into staging dir: failed to unpack the plugin archive: checksum does not match, want: 121b0f750bfc3c917cccde49999f5fa09dc405f6a4896be0f8d8d3099c5d3dee, got 121b0f750bfc3c917cccde49999f5fa09dc405f6a4896be0f8d8d3099c5d3ded
sigs.k8s.io/krew/cmd/krew/cmd.init.1.func1
	/Users/ahmetb/workspace/krew/cmd/krew/cmd/install.go:142
github.com/spf13/cobra.(*Command).execute
	/Users/ahmetb/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:762
github.com/spf13/cobra.(*Command).ExecuteC
	/Users/ahmetb/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852
github.com/spf13/cobra.(*Command).Execute
	/Users/ahmetb/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
sigs.k8s.io/krew/cmd/krew/cmd.Execute
	/Users/ahmetb/workspace/krew/cmd/krew/cmd/root.go:54
main.main
	/Users/ahmetb/workspace/krew/cmd/krew/main.go:24
runtime.main
	/usr/local/Cellar/go/1.13.4/libexec/src/runtime/proc.go:203
runtime.goexit
	/usr/local/Cellar/go/1.13.4/libexec/src/runtime/asm_amd64.s:1357
```

there's nearly nothing helpful here and it just shows the stack trace of the cmd/install call.

We should include the stack trace from the underlying error by properly Wrapf ing.

### PR DESCRIPTION
**Pull request by ahmetb**
This preserves the stack trace for errors from installation errors.

It impacts only when -v>0 specified (as that's when stack trace is printed).

Previously:

	F1113 16:05:52.448852   29304 root.go:56] failed to install some plugins: [whoami]. error=install failed: failed to unpack into staging dir: failed to unpack the plugin archive: checksum does not match, want: 121b0f750bfc3c917cccde49999f5fa09dc405f6a4896be0f8d8d3099c5d3dee, got 121b0f750bfc3c917cccde49999f5fa09dc405f6a4896be0f8d8d3099c5d3ded
	sigs.k8s.io/krew/cmd/krew/cmd.init.1.func1
		/Users/ahmetb/workspace/krew/cmd/krew/cmd/install.go:142
	github.com/spf13/cobra.(*Command).execute
		/Users/ahmetb/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:762
	github.com/spf13/cobra.(*Command).ExecuteC
		/Users/ahmetb/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852
	github.com/spf13/cobra.(*Command).Execute
		/Users/ahmetb/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
	sigs.k8s.io/krew/cmd/krew/cmd.Execute
		/Users/ahmetb/workspace/krew/cmd/krew/cmd/root.go:54
	main.main
		/Users/ahmetb/workspace/krew/cmd/krew/main.go:24
	runtime.main
		/usr/local/Cellar/go/1.13.4/libexec/src/runtime/proc.go:203
	runtime.goexit
		/usr/local/Cellar/go/1.13.4/libexec/src/runtime/asm_amd64.s:1357

With this patch:

	F1113 16:06:20.855660   29406 root.go:56] checksum does not match, want: 121b0f750bfc3c917cccde49999f5fa09dc405f6a4896be0f8d8d3099c5d3dee, got 121b0f750bfc3c917cccde49999f5fa09dc405f6a4896be0f8d8d3099c5d3ded
	sigs.k8s.io/krew/pkg/download.sha256Verifier.Verify
		/Users/ahmetb/workspace/krew/pkg/download/verifier.go:55
	sigs.k8s.io/krew/pkg/download.download
		/Users/ahmetb/workspace/krew/pkg/download/downloader.go:50
	sigs.k8s.io/krew/pkg/download.Downloader.Get
		/Users/ahmetb/workspace/krew/pkg/download/downloader.go:230
	sigs.k8s.io/krew/pkg/installation.downloadAndExtract
		/Users/ahmetb/workspace/krew/pkg/installation/install.go:148
	sigs.k8s.io/krew/pkg/installation.install
		/Users/ahmetb/workspace/krew/pkg/installation/install.go:106
	sigs.k8s.io/krew/pkg/installation.Install
		/Users/ahmetb/workspace/krew/pkg/installation/install.go:79
	sigs.k8s.io/krew/cmd/krew/cmd.init.1.func1
		/Users/ahmetb/workspace/krew/cmd/krew/cmd/install.go:120
	github.com/spf13/cobra.(*Command).execute
		/Users/ahmetb/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:762
	github.com/spf13/cobra.(*Command).ExecuteC
		/Users/ahmetb/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852
	github.com/spf13/cobra.(*Command).Execute
		/Users/ahmetb/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
	sigs.k8s.io/krew/cmd/krew/cmd.Execute
		/Users/ahmetb/workspace/krew/cmd/krew/cmd/root.go:54
	main.main
		/Users/ahmetb/workspace/krew/cmd/krew/main.go:24
	runtime.main
		/usr/local/Cellar/go/1.13.4/libexec/src/runtime/proc.go:203
	runtime.goexit
		/usr/local/Cellar/go/1.13.4/libexec/src/runtime/asm_amd64.s:1357
	failed to unpack the plugin archive
	sigs.k8s.io/krew/pkg/installation.downloadAndExtract
		/Users/ahmetb/workspace/krew/pkg/installation/install.go:149
	sigs.k8s.io/krew/pkg/installation.install
		/Users/ahmetb/workspace/krew/pkg/installation/install.go:106
	sigs.k8s.io/krew/pkg/installation.Install
		/Users/ahmetb/workspace/krew/pkg/installation/install.go:79
	sigs.k8s.io/krew/cmd/krew/cmd.init.1.func1
		/Users/ahmetb/workspace/krew/cmd/krew/cmd/install.go:120
	github.com/spf13/cobra.(*Command).execute
		/Users/ahmetb/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:762
	github.com/spf13/cobra.(*Command).ExecuteC
		/Users/ahmetb/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852
	github.com/spf13/cobra.(*Command).Execute
		/Users/ahmetb/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
	sigs.k8s.io/krew/cmd/krew/cmd.Execute
		/Users/ahmetb/workspace/krew/cmd/krew/cmd/root.go:54
	main.main
		/Users/ahmetb/workspace/krew/cmd/krew/main.go:24
	runtime.main
		/usr/local/Cellar/go/1.13.4/libexec/src/runtime/proc.go:203
	runtime.goexit
		/usr/local/Cellar/go/1.13.4/libexec/src/runtime/asm_amd64.s:1357
	failed to unpack into staging dir
	sigs.k8s.io/krew/pkg/installation.install
		/Users/ahmetb/workspace/krew/pkg/installation/install.go:107
	sigs.k8s.io/krew/pkg/installation.Install
		/Users/ahmetb/workspace/krew/pkg/installation/install.go:79
	sigs.k8s.io/krew/cmd/krew/cmd.init.1.func1
		/Users/ahmetb/workspace/krew/cmd/krew/cmd/install.go:120
	github.com/spf13/cobra.(*Command).execute
		/Users/ahmetb/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:762
	github.com/spf13/cobra.(*Command).ExecuteC
		/Users/ahmetb/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852
	github.com/spf13/cobra.(*Command).Execute
		/Users/ahmetb/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
	sigs.k8s.io/krew/cmd/krew/cmd.Execute
		/Users/ahmetb/workspace/krew/cmd/krew/cmd/root.go:54
	main.main
		/Users/ahmetb/workspace/krew/cmd/krew/main.go:24
	runtime.main
		/usr/local/Cellar/go/1.13.4/libexec/src/runtime/proc.go:203
	runtime.goexit
		/usr/local/Cellar/go/1.13.4/libexec/src/runtime/asm_amd64.s:1357
	install failed
	sigs.k8s.io/krew/pkg/installation.Install
		/Users/ahmetb/workspace/krew/pkg/installation/install.go:87
	sigs.k8s.io/krew/cmd/krew/cmd.init.1.func1
		/Users/ahmetb/workspace/krew/cmd/krew/cmd/install.go:120
	github.com/spf13/cobra.(*Command).execute
		/Users/ahmetb/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:762
	github.com/spf13/cobra.(*Command).ExecuteC
		/Users/ahmetb/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852
	github.com/spf13/cobra.(*Command).Execute
		/Users/ahmetb/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
	sigs.k8s.io/krew/cmd/krew/cmd.Execute
		/Users/ahmetb/workspace/krew/cmd/krew/cmd/root.go:54
	main.main
		/Users/ahmetb/workspace/krew/cmd/krew/main.go:24
	runtime.main
		/usr/local/Cellar/go/1.13.4/libexec/src/runtime/proc.go:203
	runtime.goexit
		/usr/local/Cellar/go/1.13.4/libexec/src/runtime/asm_amd64.s:1357
	failed to install some plugins: [whoami]. error=%!v(MISSING)
	sigs.k8s.io/krew/cmd/krew/cmd.init.1.func1
		/Users/ahmetb/workspace/krew/cmd/krew/cmd/install.go:142
	github.com/spf13/cobra.(*Command).execute
		/Users/ahmetb/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:762
	github.com/spf13/cobra.(*Command).ExecuteC
		/Users/ahmetb/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852
	github.com/spf13/cobra.(*Command).Execute
		/Users/ahmetb/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
	sigs.k8s.io/krew/cmd/krew/cmd.Execute
		/Users/ahmetb/workspace/krew/cmd/krew/cmd/root.go:54
	main.main
		/Users/ahmetb/workspace/krew/cmd/krew/main.go:24
	runtime.main
		/usr/local/Cellar/go/1.13.4/libexec/src/runtime/proc.go:203
	runtime.goexit
		/usr/local/Cellar/go/1.13.4/libexec/src/runtime/asm_amd64.s:1357

Fixes #384.

### CODE REVIEW

**Comment by ahmetb** [comment]
I must note with this change we now get a less readable error message (because the error is duplicated):

```
Installing plugin: whoami
W1113 16:12:33.677035   30130 install.go:128] failed to install plugin "whoami": install failed: failed to unpack into staging dir: failed to unpack the plugin archive: checksum does not match, want: 121b0f750bfc3c917cccde49999f5fa09dc405f6a4896be0f8d8d3099c5d3dee, got 121b0f750bfc3c917cccde49999f5fa09dc405f6a4896be0f8d8d3099c5d3ded
F1113 16:12:33.677192   30130 root.go:58] failed to install some plugins: [whoami]: install failed: failed to unpack into staging dir: failed to unpack the plugin archive: checksum does not match, want: 121b0f750bfc3c917cccde49999f5fa09dc405f6a4896be0f8d8d3099c5d3dee, got 121b0f750bfc3c917cccde49999f5fa09dc405f6a4896be0f8d8d3099c5d3ded
```

File: cmd/krew/cmd/install.go [hunk 1]
```diff
@@ -135,7 +139,7 @@ Remarks:
 				internal.PrintSecurityNotice()
 			}
 			if len(failed) > 0 {
-				return errors.Errorf("failed to install some plugins: %+v", failed)
+				return errors.Wrapf(returnErr,"failed to install some plugins: %+v", failed)
```
Comment (corneliusweig) [inline cmd/krew/cmd/install.go]: Why not simply
```suggestion
				return returnErr
```

Each failed plugin is already printed in line 128.

Comment (corneliusweig) [inline cmd/krew/cmd/install.go]: Also, the space after `returnErr,` is missing.

Comment (ahmetb) [reply cmd/krew/cmd/install.go]: I'm thinking we can just wrap as `plugin install error` wdyt?

wrapping helps a lot as we've seen in other bug reports.

Comment (ahmetb) [reply cmd/krew/cmd/install.go]: I mean yes, there's quite a bit of overlap with 128.
maybe we should unwrap the error in 128 to its root cause, im not sure.

Comment (corneliusweig) [reply cmd/krew/cmd/install.go]: Then let's keep the current version. When installing multiple plugins, this shows a full list of failed plugins which might help.

Comment (ahmetb) [reply cmd/krew/cmd/install.go]: Yeah the worst part of this is most people don't install multiple plugins at a time, but this makes the error message 2x longer by duplicating a long error message for everybody.

Comment (corneliusweig) [reply cmd/krew/cmd/install.go]: :thinking: But they should see a long stack-trace too, right? Basically, I'm ok with both options. Your call :)

Comment (ahmetb) [reply cmd/krew/cmd/install.go]: I'm not too worried about not having stack trace (%+v) at line 128 –again, since, most users install plugins one-by-one and we have decent error-wrapping.
