### PR TITLE
lint: enable errcheck and fix some issues

### LINKED ISSUE #325: Consider enabling errcheck linter
`errcheck` is in general a useful linter but it's disabled at the moment. Unless there is a specific reason to disable it, we might consider enabling it.

/kind cleanup
/kind proposal

### PR DESCRIPTION
**Pull request by ferhatelmas**
* add `.errcheck-excluded.txt` to disable some function calls as an example
* fixes #325

### CODE REVIEW

**Comment by ferhatelmas** [comment]
I had added `fixes` keyword but it seems not allowed so changed it to `related to`.

File: cmd/validate-krew-manifest/main.go [hunk 1]
```diff
@@ -40,7 +40,10 @@ var flManifest string
 
 func init() {
 	flag.StringVar(&flManifest, "manifest", "", "path to plugin manifest file")
-	flag.Set("logtostderr", "true") // Set glog default to stderr
+	// Set glog default to stderr
+	if err := flag.Set("logtostderr", "true"); err != nil {
+		glog.Fatal(err)
```
Comment (ahmetb) [inline cmd/validate-krew-manifest/main.go]: I think it would be good to use fmt.Println + os.Exit here, as glog is currently not initialized probably.

File: cmd/krew/cmd/root.go [hunk 2]
```diff
@@ -62,13 +62,16 @@ func Execute() {
...
-	flag.CommandLine.Parse([]string{}) // convince pkg/flag we parsed the flags
+	_ = flag.CommandLine.Parse([]string{}) // convince pkg/flag we parsed the flags
 	flag.CommandLine.VisitAll(func(f *flag.Flag) {
 		if f.Name != "v" { // hide all glog flags except for -v
 			pflag.Lookup(f.Name).Hidden = true
 		}
 	})
-	flag.Set("logtostderr", "true") // Set glog default to stderr
+	// Set glog default to stderr
+	if err := flag.Set("logtostderr", "true"); err != nil {
```
Comment (ahmetb) [inline cmd/krew/cmd/root.go]: glog might not be initialized yet.
maybe use fmt.Println+os.Exit(1)

**Comment by corneliusweig** [comment]
Looks good to me. Thanks for getting this done!

Have you tried changing the PR description from "related to #325" to "fixes #325"? I think it's only forbidden in commit messages but fine in PR descriptions.

File: .errcheck-excluded.txt [hunk 3]
```diff
@@ -0,0 +1,2 @@
+os.MkdirAll
```
Comment (corneliusweig) [inline .errcheck-excluded.txt]: Would it also be possible to explicitly ignore errors in the exact locations where we want to ignore errors. Like so:
```go
_ = os.MkdirAll(...)
```

Comment (ferhatelmas) [reply .errcheck-excluded.txt]: definitely. Then we shouldn't have this file.

**Comment by ferhatelmas** [comment]
> I think it's only forbidden in commit messages but fine in PR descriptions.

@corneliusweig updated and seems so.

File: .errcheck-excluded.txt (hunk 3 above)
Comment (ferhatelmas) [reply .errcheck-excluded.txt]: yes, it's possible. For being explicit, I dropped this file.

Comment (ahmetb) [inline .errcheck-excluded.txt]: since it's just 2 lines or possibly even 1, let's just drop this file if possible and call errcheck with --flags. it's kinda annoying to have an extra file in repo root just for this.

Comment (ferhatelmas) [reply .errcheck-excluded.txt]: yes, dropped. Will push soon.

**Comment by ferhatelmas** [comment]
> Looking at this a little more, I do not understand why some errors are not reported. For example, in pkg/receiptsmigration/migration_test.go:66 there is a Setenv call which returns an unhandled error that is not reported. On the other hand, the unhandled MkdirAll error in line 72 is reported. So what is the logic behind reporting some but not all errors?

It seems a bug from golangci-lint. Even if errcheck reports it, golangci-lint doesn't report it. Reported https://github.com/golangci/golangci-lint/issues/657

File: cmd/validate-krew-manifest/main.go (hunk 1 above)
Comment (ferhatelmas) [reply cmd/validate-krew-manifest/main.go]: updated as suggested.

File: cmd/krew/cmd/root.go (hunk 2 above)
Comment (ferhatelmas) [reply cmd/krew/cmd/root.go]: updated as suggested.

File: .errcheck-excluded.txt (hunk 3 above)
Comment (ferhatelmas) [reply .errcheck-excluded.txt]: pushed.

**Comment by corneliusweig** [comment]
/lgtm
waiting for @ahmetb to approve.
