### PR TITLE
cmd: Friendly error messages when plugin not found

### LINKED ISSUE #431: Improve some of the error messaging when a plugin manifest does not exist or does not support a specific platform
Some of the messaging around "not found" plugins can be confusing. Here are a few examples:

installing a non-existent plugin
```
$ KREW_ROOT="$PWD/playground" out/bin/krew-linux_amd64 install asdf --no-update-index
F1209 09:09:12.024536    3214 root.go:58] failed to load plugin "asdf" from the index: open /home/kimc/go/src/sigs.k8s.io/krew/playground/index/plugins/asdf.yaml: no such file or directory
```

upgrading plugin when manifest is deleted
```
$ KREW_ROOT="$PWD/playground" out/bin/krew-linux_amd64 upgrade grep --no-update-index
F1208 22:47:56.737799    8298 root.go:58] failed to load the plugin manifest for plugin grep: open /home/kimc/go/src/sigs.k8s.io/krew/playground/index/plugins/grep.yaml: no such file or directory
```

installing already installed plugin but plugin manifest removed from index
```
$ KREW_ROOT="$PWD/playground" out/bin/krew-linux_amd64 install grep --no-update-index
F1209 09:11:03.179194    3735 root.go:58] failed to load plugin "grep" from the index: open /home/kimc/go/src/sigs.k8s.io/krew/playground/index/plugins/grep.yaml: no such file or directory
```

The error that gets printed could be updated based on a check like `errors.Is(err, os.ErrNotExist)` for the first two. The last one should probably see that the plugin is already installed and mention something about that rather than trying to load the manifest again.

This issue was created after some discussion in https://github.com/kubernetes-sigs/krew/issues/421

### PR DESCRIPTION
**Pull request by chriskim06**
Fixes #431 

I decided to just use `os.IsNotExist` on the error rather than `errors.Is` since there's a package name conflict with the existing `github.com/pkg/errors` package. I was thinking about using the new %w verb in `fmt.Errorf` but noticed that you lose stack trace info when setting the log level. There's an existing issue, https://github.com/kubernetes-sigs/krew/issues/414, that is open to consider using 1.13 logging so I figured I'd use this for now and we could change it when the other issue gets figured out.

### CODE REVIEW

**Comment by ahmetb** [comment]
/hold
let's hold off on this until #429 is merged, there's a fair amount of merge conflicts involved.

**Comment by ahmetb** [comment]
> I decided to just use `os.IsNotExist` on the error rather than `errors.Is` since

I think this wouldn't work currently, because (1) github/pkg/errors.Wrap doesn't wrap the errors in a way the new go1.13 errors.Is() can use (2) the rest of the codebase must migrate to the errors package properly before we start incorporating parts of it.

File: cmd/krew/cmd/install.go [hunk 1]
```diff
@@ -85,10 +85,23 @@ Remarks:
...
+			installed, err := installation.ListInstalledPlugins(paths.InstallReceiptsPath())
+			if err != nil {
+				return errors.Wrap(err, "failed to find all installed versions")
+			}
+			skipped := false
 			var install []index.Plugin
 			for _, name := range pluginNames {
+				if _, ok := installed[name]; ok {
+					fmt.Fprintf(os.Stderr, "plugin \"%s\" is already installed\n", name)
+					skipped = true
```
Comment (ahmetb) [inline cmd/krew/cmd/install.go]: I'm not sure what this part does. We already have the skipping behavior implemented (see below), we can't implement it again like this. I don't see how this changes anything?

```
$ kubectl krew install krew
Updated the local copy of plugin index.
Installing plugin: krew
W1209 19:07:29.190869   69309 install.go:124] Skipping plugin "krew", it is already installed
```

Comment (ahmetb) [reply cmd/krew/cmd/install.go]: I guess it helps us not look up the deleted manifest of a plugin that's already installed. I don't think we need this, the error you added below does a proper job.

File: cmd/krew/cmd/install.go [hunk 2]
```diff
@@ -85,10 +85,23 @@ Remarks:
...
+					continue
+				}
 				plugin, err := indexscanner.LoadPluginFileFromFS(paths.IndexPluginsPath(), name)
 				if err != nil {
+					if os.IsNotExist(err) {
+						return fmt.Errorf("plugin \"%s\" does not exist in the plugin index", name)
```
Comment (ahmetb) [inline cmd/krew/cmd/install.go]: you can use %q.
and also please use `errors.New`, as it creates a stacktrace.

File: cmd/krew/cmd/install.go (hunk 1 above)
Comment (chriskim06) [reply cmd/krew/cmd/install.go]: I thought that skipping the manifest lookup for an already installed plugin and displaying a different message was what we wanted for this based on your comment [here](https://github.com/kubernetes-sigs/krew/issues/421#issuecomment-563102188):

> ...  we try to load manifest from fs again, I wonder why. we should be treating it like ErrAlreadyInstalled and say it's already installed

If its not necessary I can totally remove it, but I thought it seemed a little nicer.

Another reason I added it was for the case when the plugin(s) that are being installed don't exist so that the help message doesn't get printed. It felt out of place to show that as well.

Comment (ahmetb) [reply cmd/krew/cmd/install.go]: Yeah, I think it's making the code unnecessarily more complex and it solves a small problem that rarely occurs if ever (installing an installed plugin directly by name, after its manifest is which occurred after installing it for the first time). Let's abandon this.

**Comment by ahmetb** [comment]
/retitle cmd: Friendly error messages when plugin not found

File: cmd/krew/cmd/install.go (hunk 1 above)
Comment (chriskim06) [reply cmd/krew/cmd/install.go]: Sounds good, I'll remove it

File: cmd/krew/cmd/install.go [hunk 3]
```diff
@@ -89,6 +89,9 @@ Remarks:
 			for _, name := range pluginNames {
 				plugin, err := indexscanner.LoadPluginFileFromFS(paths.IndexPluginsPath(), name)
 				if err != nil {
+					if os.IsNotExist(err) {
+						return errors.New(fmt.Sprintf("plugin %q does not exist in the plugin index", name))
```
Comment (ahmetb) [inline cmd/krew/cmd/install.go]: sorry for back and forth but you can use errors.Errorf for this :)

Comment (chriskim06) [reply cmd/krew/cmd/install.go]: No worries, I'll make the change tomorrow

**Comment by ahmetb** [comment]
/lgtm
/approve
/hold cancel
I'm cancelling hold b/c now this is simple enough for me to rebase the other pr.
