### PR TITLE
integration_test: Refine cmd run utilities

### LINKED ISSUE #561: integration_test: RunOrFailOutput + RunOrFail is redundant
I noticed that integration tests with `.RunOrFail()` actually fail not so useful error messages like `krew [index add]: exit error 255`.

Further exploration revealed that there's actually no value add of `.RunOrFail()`.

image

/good-first-issue
/help

### PR DESCRIPTION
**Pull request by ahmetb**
- refactored ITest.Run() to return ([]byte,error)
- refactored all Run*** methods to use ITest.Run()

This also will help us test commands that are expected to fail but were
previously not making their stdout/stderr available to the test case for
string tests.

Fixes #561
/assign @corneliusweig

### CODE REVIEW

File: integration_test/testutil_test.go [hunk 1]
```diff
@@ -205,48 +205,46 @@ func (it *ITest) WithStdin(r io.Reader) *ITest {
...
 	start := time.Now()
 	if err := cmd.Run(); err != nil {
-		return errors.Wrapf(err, "krew %v", it.args)
+		out := b.Bytes()
+		return out, errors.Wrapf(err, "krew %v: %v, %s", it.args, err, string(out))
 	}
-
 	it.t.Log("Ran in", time.Since(start))
-	return nil
+	return b.Bytes(), nil
```
Comment (corneliusweig) [inline integration_test/testutil_test.go:229]: This can be simpler:
```go
err := cmd.Run()
it.t.Log("Ran in", time.Since(start))
return b.Bytes(), errors.Wrapf(err, "krew %v: %v, %s", it.args, err, string(out))
```
WDYT?

File: integration_test/testutil_test.go [hunk 2]
```diff
@@ -205,48 +205,46 @@ func (it *ITest) WithStdin(r io.Reader) *ITest {
...
+}
+
+// RunOrFail runs the krew command and fails the test if the command returns an error.
+func (it *ITest) RunOrFail() {
```
Comment (corneliusweig) [inline integration_test/testutil_test.go:233]: Is that still used? IMO we can also get rid of it and make the `t.Fatal(..)` more visible in the calling code. But this doesn't have to be here.

File: integration_test/testutil_test.go [hunk 3]
```diff
@@ -205,48 +205,46 @@ func (it *ITest) WithStdin(r io.Reader) *ITest {
...
-	if err := it.Run(); err != nil {
-		it.t.Fatal(err)
-	}
-}
-
-// Run runs the krew command.
-func (it *ITest) Run() error {
+// Run runs the krew command, and returns its combined output even when
+// it fails.
+func (it *ITest) Run() ([]byte, error) {
```
Comment (corneliusweig) [inline integration_test/testutil_test.go:210]:
```suggestion
func (it *ITest) Run() (string, error) {
```
I could be mistaken, but I think we literally _everywhere_ convert the returned byte array to a string. So we could just move the conversion into this helper.

File: integration_test/testutil_test.go (hunk 1 above)
Comment (ahmetb) [reply integration_test/testutil_test.go:229]: yeah 👍  seems like it except we need to call `b.Bytes()` only once

File: integration_test/testutil_test.go (hunk 2 above)
Comment (ahmetb) [reply integration_test/testutil_test.go:233]: yeah this has 33 use cases, so it helps us save 33 `if err := ... ; err != nil { t.fatalf }` blocks :)

File: integration_test/testutil_test.go (hunk 3 above)
Comment (ahmetb) [reply integration_test/testutil_test.go:210]: `RunOrFailOutput` is `[]byte` so I kept it consistent w/ that.
We can convert both to `string` in another PR, wanted to keep this patch short.

**Comment by corneliusweig** [comment]
/lgtm
/approve
Thanks for honing our test utils. This is worth so much!
