### PR TITLE
Consider HTTP status for more meaningful errors

### LINKED ISSUE #516: add details to Test_fetchLatestTag_GitHubAPI
```
--- FAIL: Test_fetchLatestTag_GitHubAPI (0.16s)
    fetch_tag_test.go:29: Expected a latest tag in the response
FAIL
```

This test is very frequently failing on Travis CI.

I'm guessing because of GitHub API rate limits exposed to pool of Travis CI machines. Surprisingly works fine on GitHub Actions, however.

Maybe it'd be ideal if we add some message to the error so we can see what's going on.

### PR DESCRIPTION
**Pull request by corneliusweig**
The krew CI has quite a few problems on travis, supposedly due to
API quota violation. For more meaningful errors, we now consider the
HTTP status code of the GitHub API response.

Fixes #516

### CODE REVIEW

**Comment by corneliusweig** [comment]
Let's hope the travis build is red :D

**Comment by corneliusweig** [comment]
Let's hope the travis build is red :laughing:

File: cmd/krew/cmd/internal/fetch_tag.go [hunk 1]
```diff
@@ -36,6 +36,9 @@ func FetchLatestTag() (string, error) {
 	if err != nil {
 		return "", errors.Wrapf(err, "could not GET the latest release")
 	}
+	if response.StatusCode != http.StatusOK {
+		return "", errors.Errorf("expected HTTP status 200 OK, got %s", response.Status)
```
Comment (ahmetb) [inline cmd/krew/cmd/internal/fetch_tag.go]: can we do %d as well (and use response.StatusCode)?

Comment (corneliusweig) [reply cmd/krew/cmd/internal/fetch_tag.go]: I think the status code is part of the string. For example for status 200, its `"200 OK"`.

**Comment by corneliusweig** [comment]
/hold cancel
I moved the `defer` statement up.

**Comment by corneliusweig** [comment]
Ah.. finally. Took only 4 tries to get travis red :octopus:
I didn't expect 403 though:
```
fetch_tag_test.go:26: expected HTTP status 200 OK, got 403 Forbidden
```

---

@ahmetb should we disable this test for the time being? Or skip for short tests `testing.Short()`? After all, this still prevents us from merging with Prow.

**Comment by ahmetb** [comment]
Good lord, lets just delete that test.

**Comment by corneliusweig** [comment]
Really? If I remember correctly you were strongly in favor of having it :wink: 

I'll disable it for now.

**Comment by ahmetb** [comment]
Yeah, let's add a `// TODO enable once Travis CI is discontinued` which we should probably do soon anyway.

**Comment by corneliusweig** [comment]
Ok, the test is skipped now and I added the todo.
